### ISSUE TITLE
Segmentation fault in rational test_numpy_cast()

### ISSUE THREAD

**Issue by taldcroft** [numpy/numpy-dtypes#4]
I get a segmentation fault when running the `test_numpy_cast()` function in `test_rational.py` at line 187.  This is on linux (CentOS-5) using a recent version of numpy development master.

https://github.com/numpy/numpy-dtypes/blob/master/npytypes/rational/test_rational.py#L187

**Comment by seberg** [comment]
I am going to archive this repository.  We have new-style DTypes and this has been inactive for many years.  At this point development from the NumPy side should go towards new ones.

(There will be a new repository to start examples using the new DType API.)
